config/routes.rb
Rails.application.routes.draw do

  root 'site_pages#home'

  get '/about', to: 'site_pages#about'
  get '/services', to: 'site_pages#services'

  get '/contact', to: 'contacts#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    # @contact = Contact.new
  end

  def create
    # @contact = Contact.new(params[:contact])
    # @contact.request = request
    # if @contact.deliver
    #   flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    #   render :new
    # else
    #   flash.now[:alert] = 'Cannot send message.'
    #   render :new
    # end
  end
end

app/controllers/site_pages_controller.rb
class SitePagesController < ApplicationController
  def home
  end

  def about
  end

  def services
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
      <div>
        <a href="#" data-dismiss="alert">×</a>
        <%= value %>
      </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>
<% provide(:row_info, 'Contact Us') %>

<div class="container">
  <h2>Contact</h2>
  <div class="row" id="contact">
    <%= render 'shared/flash_msg' %>
    <div class="col-sm-8">
      <p>
        We'd love to hear from you. Fill the form below to make a booking or ask questions.
        Your details will be kept private.
      </p>
      <div class="jumbotron" id="form_container">
        <%= simple_form_for @contact do |f| %>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, required: true, class: 'form-control', placeholder: 'First and last name please' %>
                  <%= f.label :phone %>
                  <%= f.phone_field :phone, class: 'form-control', placeholder: 'What is your phone number?' %>
                  <%= f.label :email %>
                  <%= f.email_field :email, required: true, class: 'form-control', placeholder: 'What is your email address?' %>
                  <div class= "hidden">
                    <%= f.input :nickname, :hint => 'Leave this field blank!' %>
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <label for="comments">Comment/Questions:</label>
                <%= f.text_area :comments, required: true, class: 'form-control', placeholder: 'Write your message here!' %>
              </div>
            </div>
            <%= f.submit 'Submit', class: 'btn btn-primary pull-right' %>
        <% end %>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="jumbotron" id="contact-details">
        <h4><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Company Addresses</h4>
        <address>
          <strong>ESABOL Juice and Smoothie Bar</strong><br>
          Dwarf Shop 3<br>
          FUTA Community Shopping Plaza<br>
          Oba-Nla Campus, FUTA<br>
          Akure, Nigeria.
        </address>
        <address>
          <strong>ESABOL Juice and Smoothie Bar</strong><br>
          FUTA Sports Complex<br>
          Behind Hilltop Auditorium<br>
          Oba-Nla Campus, FUTA<br>
          Akure, Nigeria.
        </address>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_carousel.html.erb
<div id="pictures" class="col-sm-12 owl-carousel owl-theme">
  <div class="item" id="slide-1"><%= image_tag 'fullimage1.jpg', alt: 'Slide 1' %></div>
  <div class="item" id="slide-2"><%= image_tag 'fullimage2.jpg', alt: 'Slide 2' %></div>
  <div class="item" id="slide-3"><%= image_tag 'fullimage3.jpg', alt: 'Slide 3' %></div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer container-fluid">
  <div class="container">
    <div id="footer-row-1" data-role="footer" class="row">
      <div class="col-sm-4">
        <h4>
          <%= image_tag 'DeoParakletos_2.png', alt: 'Deo Parakletos', class: 'name' %><br>
        </h4>
        <p>
          Deo Parakletos Specialist Clinic is here to fix any health concern you might have. Our team of friendly physicians
          and consultants will make you for once feel comfortable while we attend to your medical needs.
        </p>
        <br>
        <h4>Contact us</h4>
        <div>
          <a><i class="fa fa-mobile-phone fa-2x pull-left"></i></a>
          <a href="tel:08062283308">08062283308</a><br>
          <a href="tel:08033978237">08033978237</a>
        </div>
        <br>
        <div>
          <a><i class="fa fa-envelope fa-lg pull-left"></i></a>&nbsp
          <a href="mailto:info@deoparakletos.org">info@deoparakletos.org</a>
        </div>
      </div>
      <div class="col-sm-4">
        <h4>Opening hours</h4>
        <div>
          <i class="fa fa-clock-o fa-3x pull-left"></i>
          <span>Monday-Friday: 9am-6pm</span><br>
          <span>Saturday: 10am-4pm</span><br>
          <span>Sunday: 10am-1pm</span>
        </div>
        <br>
        <h4>
          <i class="fa fa-quote-left fa-2x pull-left"></i>
          Take care of your body; it's the only place you have to live in.
        </h4>
      </div>
      <div class="row col-sm-4 text-center">
        <h4 class="text-left">Locate Us</h4>
        <iframe
            width="200"
            height="200"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCK4A2GUKhzcS7y43Fhonr8PVob1I3cd_4&q=Afrosoft+Akure" allowfullscreen>
        </iframe>
        <address class="text-left">
          <i class="fa fa-map-marker fa-3x pull-left"></i>
          <strong>Deo Parakletos Specialist Clinic</strong><br>
          Road L, Afrosoft Estate,<br>
          Adjacent SIB<br>
          Igbatoro Road, Akure, Nigeria.
        </address>
      </div>
    </div>
    <br>
    <div id="footer-row-2" class="row">
      <%= link_to (image_tag 'DeoParakletos.png', alt: 'Deo Parakletos', class: 'footer-logo'), root_path %><br>
      &copy <%= Time.zone.now.year %>. All rights reserved.<br>
      <small>Deo Parakletos Specialist Clinic is a subsidiary of Deo Parakletos Investment Limited.</small>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header id="navbar" class="navbar navbar-default" role="navigation">
  <div id="topmost">
    <div class="container">
      <span>
        <a><i class="fa fa-mobile-phone fa-lg"></i></a>&nbsp
        <a href="tel:08062283308">08062283308</a>
      </span>
      <span class="pull-right">
        <a><i class="fa fa-facebook fa-lg"></i></a> &nbsp
        <a><i class="fa fa-google-plus fa-lg"></i></a> &nbsp
        <a><i class="fa fa-twitter fa-lg"></i></a> &nbsp
        <a><i class="fa fa-whatsapp fa-lg"></i></a>
      </span>
    </div>
  </div>
  <div class="container second-top">
    <%=image_tag 'DeoParakletos.png', class: 'logo' %>
  </div>
    <div id="links_container">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header" id="navbar-header">
          <span class="pull-left navbar-toggle collapsed">MENU</span>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <nav class="collapse navbar-collapse" id="navbar-collapse">
          <ul id="nav-links" class="nav navbar-nav">
            <li><%= nav_link_to 'HOME', root_path %></li>
            <li><%= nav_link_to 'ABOUT', about_path %></li>
            <li><%= nav_link_to 'SERVICES', services_path %></li>
          </ul>
        </nav><!-- /.navbar-collapse -->
      </div>
    </div><!-- /.container-fluid -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href='https://fonts.googleapis.com/css?family=Roboto:400,400italic' rel='stylesheet' type='text/css'>
      <%= favicon_link_tag 'favicon.png' %>
      <title>Deo Parakletos</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <%= render 'shared/flash_msg' %>
        <div>
          <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/shared/_flash_msg.html.erb
<% if notice %>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
<% end %>

app/views/site_pages/about.html.erb
<% provide(:title, 'About') %>
<% provide(:row_info, 'About Us') %>

<div class="container-fluid">

</div>

app/views/site_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% provide(:row_info, 'Contact Us') %>

<div class="container">
  <h2>Contact</h2>
  <div class="row" id="contact">
    <div class="col-sm-8">
      <p>
        We'd love to hear from you. Fill the form below to make a booking or ask questions.
        Your details will be kept private.
      </p>
      <div class="jumbotron">
        <%= simple_form_for @contact do |f| %>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, required: true, class: 'form-control', placeholder: 'First and last name please' %>
                  <%= f.label :phone %>
                  <%= f.phone_field :phone, class: 'form-control', placeholder: 'What is your phone number?' %>
                  <%= f.label :email %>
                  <%= f.email_field :email, required: true, class: 'form-control', placeholder: 'What is your email address?' %>
                </div>
              </div>
              <div class="col-sm-6">
                <label for="comments">Comment/Questions:</label>
                <%= f.text_area :comments, required: true, class: 'form-control', placeholder: 'Write your message here!' %>
              </div>
            </div>
            <%= f.submit 'Submit', class: 'btn btn-primary pull-right' %>
        <% end %>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="jumbotron" id="contact-details">
        <h4><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Company Addresses</h4>
        <address>

        </address>
        <address>

        </address>
      </div>
    </div>
  </div>
</div>

app/views/site_pages/home.html.erb
<%= render 'layouts/carousel' %>
<br xmlns="http://www.w3.org/1999/html">
<div class="container">
  <div id="row-2" class="row text-center">
    <br>
    <div class="col-sm-4 text-left block-details">
      <i class="fa fa-stethoscope fa-3x pull-right blue" aria-hidden="true"></i>
      <h4>
        <span class="service-heading blue">24/7 Healthcare<br>and counseling</span>
      </h4>
      <p>
        <br>
        God heals, we care. We are always available, 24 hours a day, 7 days a week.
      </p>
      <a class="btn btn-default">READ MORE</a>
    </div>

    <div class="col-sm-4 text-left block-details">
      <i class="fa fa-heartbeat fa-3x pull-right blue" aria-hidden="true"></i>
      <h4>
        <span class="service-heading blue">Kidney-related<br>counseling</span>
      </h4>
      <p>
        <br>
        We have on our team world class consultant nephrologists.
      </p>
      <a class="btn btn-default">READ MORE</a>
    </div>

    <div class="col-sm-4 text-left block-details">
      <i class="fa fa-user-md fa-3x pull-right blue" aria-hidden="true"></i>
      <h4>
        <span class="service-heading blue">Endocrine gland and<br>hormone counseling</span>
      </h4>
      <p>
        <br>
        We also have on our team world class consultant endocrinologists.
      </p>
      <a class="btn btn-default">READ MORE</a>
    </div>
  </div>
</div>
<br>
<div class="container-fluid">
  <div id="row-3" class="row text-center">
    <div class="container">
      <h3>Why choose Deo Parakletos<i class="fa fa-question-circle-o fa-1x"></i></h3><br>
      <div class="col-sm-3">
        <i class="fa fa-group fa-4x"></i><br>
        <h4>Experience</h4>
        <p>
          With our team of experienced and well qualified physicians and consultants, you're in safe hands.
        </p>
      </div>
      <div class="col-sm-3">
        <i class="fa fa-thumbs-o-up fa-4x"></i><br>
        <h4>Quality of service</h4>
        <p>
          You will enjoy world class treatment in a very conducive environment. Come check it out!
        </p>
      </div>
      <div class="col-sm-3">
        <i class="fa fa-clock-o fa-4x"></i><br>
        <h4>Flexible schedule</h4>
        <p>
          We are available for you at any time. We're just one phone call away. Dial that number now!
        </p>
      </div>
      <div class="col-sm-3">
        <i class="fa fa-group fa-4x"></i><br>
        <h4>Testimonial</h4>
        <p>
          People speak well of us. Our patients have not had it better anywhere else. A trial will convince you.
        </p>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div id="row-4" class="row text-center">
    <h3>Our Directors</h3>
    <br>
    <div class="col-sm-6 doctor">
      <h4 class="doctor-bio">
        <i class="fa fa-user-md fa-5x"></i><br>
        <b>Dr Olalekan Ezekiel OJO</b><br>
        <small>Consultant Physician and Nephrologist</small>
      </h4>
    </div>

    <div class="col-sm-6 doctor">
      <h4 class="doctor-bio">
        <i class="fa fa-user-md fa-5x"></i><br>
        <b>Dr Olubukola Ayoola OJO</b><br>
        <small>Consultant Physician and Endocrinologist</small>
      </h4>
    </div>
  </div>
</div>